function [electrical_series] = add_eeg_data(tbl, data)
% links electrode table to electrical series and adds eeg data

electrodes_object_view = types.untyped.ObjectView('/general/extracellular_ephys/electrodes');


% 'table' attribute is a link to another DynamicTable (in this case, the electrodes table, tbl)
% 'data' indicates the rows of the table
electrode_table_region = types.hdmf_common.DynamicTableRegion(...
    'table', electrodes_object_view, ...
    'description', 'all electrodes', ...
    'data', (0:height(tbl)-1)');


% TODO: add starting time and starting time rate info
electrical_series = types.core.ElectricalSeries( ...
    'starting_time', 0.0, ...
    'starting_time_rate', data.fsample, ...
    'data', data.wave, ...
    'electrodes', electrode_table_region, ...
    'data_unit', 'volts');

end

