function [electrode_table, tbl] = get_electrodes(sbj_name, dirs, ext_name)
%GET_ELECTRODES creates electrode table
%   creates table of electrodes that generated data. Returns both table of
%   electrode info (tbl) for visualization purposes and dynamic table of 
%   same information and categories for nwb file
%
%   INPUT:
%       sbj_name: subject name
%       dirs: directories pointing to files of interest (generated by InitializeDirs)
%       ext_name: extended version of sbj_name (used for accessing correct
%                 folders/files)
%
%   Laboratory of Behavioral and Cognitive Neuroscience, Stanford University
%   Authors: Pedro Pinheiro-Chagas, Areti Majumdar
%   Copyright: MIT License 2021  


subj_file = [dirs.original_data filesep ext_name{1} filesep 'subjVar_' ext_name{1} '.mat'];
load(subj_file);


% add to variables as you add more info
variables = {'x', 'y', 'z', 'imp', 'location', 'filtering', 'label'};
tbl = cell2table(cell(0, length(variables)), 'VariableNames', variables);

% iterate through subjVar for electrode info 
for ielec = 1:height(subjVar.elinfo)
    x = subjVar.elinfo.MNI_coord(ielec,1,1);
    y = subjVar.elinfo.MNI_coord(ielec,2,1);
    z = subjVar.elinfo.MNI_coord(ielec,3,1);
    
    imp = 'NaN';
    location = subjVar.elinfo.DK_long_josef{ielec,1}{1};
    filtering = 'common average';
    label = subjVar.elinfo.FS_label{ielec};
    
    tbl = [tbl; {x, y, z, imp, location, filtering, label}];
end


%descrip = ['all electrodes, bad channels: ' globalVar.badChan]

electrode_table = util.table2nwb(tbl, 'all electrodes');